In [1]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_values, y_values)

NameError: name 'x_values' is not defined

In [2]:
print(model.predict([ [127], 248] ]))

SyntaxError: invalid syntax (<ipython-input-2-af738a0297e3>, line 1)

In [3]:
print(model.predict([ [127], [248] ]))

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [4]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_values, y_values)
print(model.predict([ [127], [248] ]))

NameError: name 'x_values' is not defined

In [5]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_values, y_values)

NameError: name 'x_values' is not defined

In [2]:
import pandas as pd
import numpy as np
bmi_life_data = pd.read_csv('bmi_and_life_expectancy.csv')
bmi_life_data

Country  Life expectancy       BMI
0               Afghanistan             52.8  20.62058
1                   Albania             76.8  26.44657
2                   Algeria             75.5  24.59620
3                   Andorra             84.6  27.63048
4                    Angola             56.7  22.25083
5                   Armenia             72.3  25.35542
6                 Australia             81.6  27.56373
7                   Austria             80.4  26.46741
8                Azerbaijan             69.2  25.65117
9                   Bahamas             72.2  27.24594
10               Bangladesh             68.3  20.39742
11                 Barbados             75.3  26.38439
12                  Belarus             70.0  26.16443
13                  Belgium             79.6  26.75915
14                   Belize             70.7  27.02255
15                    Benin             59.7  22.41835
16                   Bhutan             70.7  22.82180
17                  Bolivia             71.2  24.43335
18   Bosnia and Herzegovina             77.5  26.61163
19                 Botswana             53.2  22.12984
20                   Brazil             73.2  25.78623
21                 Bulgaria             73.2  26.54286
22             Burkina Faso             58.0  21.27157
23                  Burundi             59.1  21.50291
24                 Cambodia             66.1  20.80496
25                 Cameroon             56.6  23.68173
26                   Canada             80.8  27.45210
27               Cape Verde             70.4  23.51522
28                     Chad             54.3  21.48569
29                    Chile             78.5  27.01542
..                      ...              ...       ...
133                   Spain             81.1  27.49975
134               Sri Lanka             74.0  21.96671
135                   Sudan             65.5  22.40484
136                Suriname             70.2  25.49887
137               Swaziland             45.1  23.16969
138                  Sweden             81.1  26.37629
139             Switzerland             82.0  26.20195
140                   Syria             76.1  26.91969
141              Tajikistan             69.6  23.77966
142                Tanzania             60.4  22.47792
143                Thailand             73.9  23.00803
144             Timor-Leste             69.9  20.59082
145                    Togo             57.5  21.87875
146                   Tonga             70.3  30.99563
147     Trinidad and Tobago             71.7  26.39669
148                 Tunisia             76.8  25.15699
149                  Turkey             77.8  26.70371
150            Turkmenistan             67.2  25.24796
151                  Uganda             56.0  22.35833
152                 Ukraine             67.8  25.42379
153    United Arab Emirates             75.6  28.05359
154          United Kingdom             79.7  27.39249
155           United States             78.3  28.45698
156                 Uruguay             76.0  26.39123
157              Uzbekistan             69.6  25.32054
158                 Vanuatu             63.4  26.78926
159      West Bank and Gaza             74.1  26.57750
160                 Vietnam             74.1  20.91630
161                  Zambia             51.1  20.68321
162                Zimbabwe             47.3  22.02660

[163 rows x 3 columns]

In [6]:
# TODO: Add import statements
import pandas as pd
from sklearn.linear_model import LinearRegression

# Assign the dataframe to this variable.
# TODO: Load the data
bmi_life_data = pd.read_csv('bmi_and_life_expectancy.csv')


# Make and fit the linear regression model
#TODO: Fit the model and Assign it to bmi_life_model
bmi_life_model = LinearRegression()
bmi_life_model.fit(bmi_life_data[['BMI']], bmi_life_data[['Life expectancy']])

# Make a prediction using the model
# TODO: Predict life expectancy for a BMI value of 21.07931
laos_life_exp = bmi_life_model.predict(21.07931)

In [5]:
# TODO: Add import statements
import pandas as pd
from sklearn.linear_model import LinearRegression

# Assign the dataframe to this variable.
# TODO: Load the data
bmi_life_data = pd.read_csv('bmi_and_life_expectancy.csv')
bmi_life_data

Country  Life expectancy       BMI
0               Afghanistan             52.8  20.62058
1                   Albania             76.8  26.44657
2                   Algeria             75.5  24.59620
3                   Andorra             84.6  27.63048
4                    Angola             56.7  22.25083
5                   Armenia             72.3  25.35542
6                 Australia             81.6  27.56373
7                   Austria             80.4  26.46741
8                Azerbaijan             69.2  25.65117
9                   Bahamas             72.2  27.24594
10               Bangladesh             68.3  20.39742
11                 Barbados             75.3  26.38439
12                  Belarus             70.0  26.16443
13                  Belgium             79.6  26.75915
14                   Belize             70.7  27.02255
15                    Benin             59.7  22.41835
16                   Bhutan             70.7  22.82180
17                  Bolivia             71.2  24.43335
18   Bosnia and Herzegovina             77.5  26.61163
19                 Botswana             53.2  22.12984
20                   Brazil             73.2  25.78623
21                 Bulgaria             73.2  26.54286
22             Burkina Faso             58.0  21.27157
23                  Burundi             59.1  21.50291
24                 Cambodia             66.1  20.80496
25                 Cameroon             56.6  23.68173
26                   Canada             80.8  27.45210
27               Cape Verde             70.4  23.51522
28                     Chad             54.3  21.48569
29                    Chile             78.5  27.01542
..                      ...              ...       ...
133                   Spain             81.1  27.49975
134               Sri Lanka             74.0  21.96671
135                   Sudan             65.5  22.40484
136                Suriname             70.2  25.49887
137               Swaziland             45.1  23.16969
138                  Sweden             81.1  26.37629
139             Switzerland             82.0  26.20195
140                   Syria             76.1  26.91969
141              Tajikistan             69.6  23.77966
142                Tanzania             60.4  22.47792
143                Thailand             73.9  23.00803
144             Timor-Leste             69.9  20.59082
145                    Togo             57.5  21.87875
146                   Tonga             70.3  30.99563
147     Trinidad and Tobago             71.7  26.39669
148                 Tunisia             76.8  25.15699
149                  Turkey             77.8  26.70371
150            Turkmenistan             67.2  25.24796
151                  Uganda             56.0  22.35833
152                 Ukraine             67.8  25.42379
153    United Arab Emirates             75.6  28.05359
154          United Kingdom             79.7  27.39249
155           United States             78.3  28.45698
156                 Uruguay             76.0  26.39123
157              Uzbekistan             69.6  25.32054
158                 Vanuatu             63.4  26.78926
159      West Bank and Gaza             74.1  26.57750
160                 Vietnam             74.1  20.91630
161                  Zambia             51.1  20.68321
162                Zimbabwe             47.3  22.02660

[163 rows x 3 columns]

In [7]:
# TODO: Add import statements
import pandas as pd
from sklearn.linear_model import LinearRegression

# Assign the dataframe to this variable.
# TODO: Load the data
bmi_life_data = pd.read_csv('bmi_and_life_expectancy.csv')


# Make and fit the linear regression model
#TODO: Fit the model and Assign it to bmi_life_model
bmi_life_model = LinearRegression()
bmi_life_model.fit(bmi_life_data[['BMI']], bmi_life_data[['Life expectancy']])

# Make a prediction using the model
# TODO: Predict life expectancy for a BMI value of 21.07931
laos_life_exp = bmi_life_model.predict(21.07931)

In [8]:
laos_life_exp

array([[60.31564716]])

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

# Load the data from the boston house-prices dataset 
boston_data = load_boston()
x = boston_data['data']
y = boston_data['target']

# Make and fit the linear regression model
# TODO: Fit the model and assign it to the model variable
model = LinearRegression()
model.fit(x,y)

# Make a prediction using the model
sample_house = [[2.29690000e-01, 0.00000000e+00, 1.05900000e+01, 0.00000000e+00, 4.89000000e-01,
                6.32600000e+00, 5.25000000e+01, 4.35490000e+00, 4.00000000e+00, 2.77000000e+02,
                1.86000000e+01, 3.94870000e+02, 1.09700000e+01]]
# TODO: Predict housing price for the sample_house
prediction = model.predict(sample_house)
prediction

array([23.68420569])

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

# Load the data from the boston house-prices dataset 
boston_data = load_boston()
x = boston_data['data']
y = boston_data['target']
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [11]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21