In [4]:
a = set()
a.add('neg')
a.add('pos')
a.add('neg')
print(a)

{'pos', 'neg'}


In [9]:
import numpy as np
a = np.zeros((1, 100))
a.shape

(1, 100)

In [11]:
a = np.random.normal(0.0, 5**-0.5, (10,5))
print(a)

[[ 0.44623779  0.27764638 -0.71098009 -0.65367588 -0.41755496]
 [ 0.17271736  0.12648202  0.54939821  0.34016512 -0.3720502 ]
 [ 0.37009761  0.55979818  0.18229602 -0.01552884  0.2525582 ]
 [ 0.54037725 -0.17954463  0.8106144   0.13288068 -0.56156226]
 [-0.12932737  0.84182541  0.6452194  -0.47142203 -0.3513694 ]
 [ 0.0264297   0.5479486   0.00977478  0.41265303  0.29876849]
 [ 0.55711405  0.43973217 -0.18900305  0.78378105 -0.2608007 ]
 [-1.36214329 -0.30819074  0.75109573  0.60356229 -0.26748242]
 [ 0.12678872 -0.80967657  0.06880732 -0.61754003 -0.02316778]
 [ 0.10333778  0.06678736 -0.52760221  0.43121827  0.03795957]]


In [12]:
a = np.zeros(5)

In [13]:
a

array([0., 0., 0., 0., 0.])

In [14]:
idx = [2, 4]
idx

[2, 4]

In [15]:
a(idx)=1
a

SyntaxError: can't assign to function call (<ipython-input-15-6138b7946790>, line 1)

In [16]:
a[idx] = 1
a

array([0., 0., 1., 0., 1.])

In [17]:
a = []
a.append(1)
a.append(2)
a

[1, 2]

In [21]:
a = []
b = []
b.append(1)
b.append(2)
a.append(b)
c = []
c.append(3)
c.append(4)
c.append(1)
a.append(c)
a
len(a)

2

In [19]:
a = list()
b = set()
b.add(1)
b.add(2)
a.append(list(b))
c = set()
c.add(3)
c.add(4)
c.add(1)
a.append(list(c))
a

[[1, 2], [1, 3, 4]]

In [20]:
len(a)

2